version: "3"
services:
    serve:
        build: ./hello_world_app/
        ports:
            - "80:8080"
    deploy:
        build: .
        command: >
            sh -c "cdk bootstrap
            && cdk synth
            && cdk deploy"
        environment:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
    destroy:
        build: .
        command: >
            sh -c "cdk destroy"
        environment:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION